### ISSUE TITLE
推送提交出现的问题

### ISSUE THREAD

**Issue by anjue39** [xhrzg2017/ProxiesActions#1]
推送更改环节总是推送不了的情况，token权限你怎么设置的？

**Comment by xhrzg2017** [comment]
Automatic token authentication 
https://docs.github.com/zh/actions/security-guides/automatic-token-authentication
Creating a personal access token
https://docs.github.com/zh/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

**Comment by anjue39** [comment]
![image](https://user-images.githubusercontent.com/98279987/229282850-32202657-315a-4850-b6a4-2d3a5dc685ef.png)
试过了，总是不行

**Comment by anjue39** [comment]
![image](https://user-images.githubusercontent.com/98279987/229283903-1bddcb04-3566-4d94-97a1-4794471c7309.png)
![image](https://user-images.githubusercontent.com/98279987/229284131-c91bd932-9f83-4e80-8379-4e47df2b04dd.png)
都做了，但是还是出现错误
![image](https://user-images.githubusercontent.com/98279987/229284379-28f08bf6-31c9-4798-bdc7-d52dd095cf26.png)

**Comment by anjue39** [comment]
![image](https://user-images.githubusercontent.com/98279987/229284490-76c41015-1ad0-4457-97d5-5d3c36969bbe.png)这个权限你勾了哪几项？
